### ISSUE TITLE
Stopped responding to commands

### ISSUE THREAD

**Issue by buvanenko** [lawxls/HackerNews-Alerts-Bot#15]
Has not responded to commands for many days, but continues to send news

![Screenshot_2023-02-04-00-07-28-404_org.telegram.messenger.jpg](https://user-images.githubusercontent.com/60255961/216710976-f5940d63-77e8-4a49-813d-5f29b1d07eeb.jpg)

**Comment by lawxls** [comment]
Celery worker responsible for sending messages went offline. Fixed
