### ISSUE TITLE
feature idea: follow user, get notified of new posts

### ISSUE THREAD

**Issue by swyxio** [lawxls/HackerNews-Alerts-Bot#18]
thanks for dropping this in HN: just throwing this in here as a feature idea!

https://news.ycombinator.com/item?id=35117535

**Comment by sw-yx** [comment]
some people on HN put their followlists in bio:

- https://news.ycombinator.com/user?id=ignoramous
- https://news.ycombinator.com/user?id=tptacek

**Comment by lawxls** [comment]
Done.
https://github.com/lawxls/HackerNews-Alerts-Bot#follow-users
