### ISSUE TITLE
Considering supporting more sources (like Reddit)?

### ISSUE THREAD

**Issue by juliensalinas** [lawxls/HackerNews-Alerts-Bot#27]
Thank you for the awesome project 💪🏻
I usually monitor keywords on both Hacker News, Reddit, and other platforms, and I'm sure many others do the same.
It would be awesome if your project could support more platforms (like [kwatch.io](https://kwatch.io) does for example, except that they don't provide a Telegram integration).
If you can't no worries and I would like to thank you again for your project!

**Comment by lawxls** [comment]
Thanks for the kind words! This project is for Hacker News forum only. And the telegram bot itself is back online after some period of inactivity.
